source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'DateInRegion_Tests', :exclusive => true do
  pod "DateInRegion", :path => "../"

  pod 'Quick', '~> 0.3.1'
  pod 'Nimble'
end
